# Generated by Django 3.1.3 on 2020-11-17 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='categories',
            name='time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.TimeField(),
        ),
    ]
