# Generated by Django 3.1.3 on 2020-11-18 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20201117_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='category',
        ),
    ]
