# Generated by Django 3.1.3 on 2020-11-18 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(),
        ),
    ]
