# Generated by Django 3.1.3 on 2020-11-17 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Timestamp',
        ),
    ]
